package com.flowpowered.commands.annotated;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface Parent {

    /**
     * Returns an array of unique command names (including the provider parts) of parent commands to which the command should be added as child.
     *
     * @return an array of parents' unique command names
     */
    public String[] value();

    /**
     * Returns an array of child names that should be used when adding the command as a child to respective {@link #value() parent commands}.
     * <p>
     * The array must have the same number of elements as the number of elements in {@link #value()}, or be empty or null.
     * If the array is empty or null, the child names will be autogenerated by truncating the {@link CommandDescription#name() unique name} of the command
     * (see {@link com.flowpowered.commands.Command#getSimpleName(String) Command.getSimpleName(String)}).
     *
     * @return array of child names as which the command should be added
     */
    public String[] childNames() default {};
}
