package com.flowpowered.commands.annotated;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface Parent {

    /**
     * Returns the unique command name (including the provider part) of the parent command to which the command should be added as child.
     *
     * @return parent's unique command name
     */
    public String value();

    /**
     * Returns the name that should be used as a child name when adding the command as a child to the {@link #value() parent command}.
     * <p>
     * If the name is an empty string or null, the child name will be autogenerated by truncating the {@link CommandDescription#name() unique name} of the command
     * (see {@link com.flowpowered.commands.Command#getSimpleName(String) Command.getSimpleName(String)}).
     *
     * @return child name as which the command should be added
     */
    public String name() default "";
}
